[package]
name = "nestle"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.release]
strip = true
opt-level = "z"       # for smallest size
lto = true            # link-time optimization
panic = "abort"       # classic Rust ;)
